"""Deterministic formal-plant calibration data generated by the numerical simulator."""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import subprocess
from time import perf_counter
from typing import Any, Literal

import numpy as np
from pydantic import BaseModel, ConfigDict, Field, model_validator

from aircraft_recovery.config import AircraftConfig, ScenarioConfig, load_config, load_yaml
from aircraft_recovery.data.hashing import canonical_hash, file_hash
from aircraft_recovery.failures import FailureDefinition, FailureType
from aircraft_recovery.models import (
    ControlCommands, ControllerOutput, NavigationCommands, SafetyDecision, StabilizationTargets,
)
from aircraft_recovery.simulator import SimpleAircraftSimulator


STATE_NAMES = (
    "airspeed_kts", "pitch_deg", "bank_deg", "vertical_speed_fpm",
    "terrain_clearance_ft", "previous_elevator", "previous_aileron",
    "previous_rudder", "previous_throttle_left", "previous_throttle_right",
)
ACTION_NAMES = ("elevator", "aileron", "rudder", "throttle_left", "throttle_right")


class PlantDatasetConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")
    protocol_version: str
    split: Literal["calibration", "validation", "development"]
    seed: int = Field(ge=0)
    one_step_samples: int = Field(gt=0)
    trace_count: int = Field(ge=0)
    trace_length_steps: int = Field(gt=0)
    pre_roll_steps: int = Field(default=3, ge=0)
    aircraft_config: str = "configs/aircraft/simple_twin.yaml"
    output_directory: str
    protocol_timestamp_utc: str
    allow_dirty_tree: bool = False
    state_ranges: dict[str, tuple[float, float]]
    failure_ranges: dict[str, tuple[float, float]]
    disturbance_ranges: dict[str, tuple[float, float]]
    sensor_error_ranges: dict[str, tuple[float, float]]

    @model_validator(mode="after")
    def bounds_are_ordered(self) -> "PlantDatasetConfig":
        required_state = {"airspeed_kts", "pitch_deg", "bank_deg", "terrain_clearance_ft"}
        required_failures = {"right_thrust_availability", "aileron_effectiveness", "actuator_delay_seconds"}
        if not required_state <= self.state_ranges.keys() or not required_failures <= self.failure_ranges.keys():
            raise ValueError("Dataset configuration is missing required state or failure ranges")
        for group in (self.state_ranges, self.failure_ranges, self.disturbance_ranges, self.sensor_error_ranges):
            if any(lower > upper for lower, upper in group.values()):
                raise ValueError("Every configured lower bound must be <= its upper bound")
        return self


class PlantTransitionRecord(BaseModel):
    model_config = ConfigDict(extra="forbid")
    schema_version: Literal[1] = 1
    split: Literal["calibration", "validation", "development"]
    record_kind: Literal["one_step", "trace"]
    sample_id: str
    scenario_id: str
    trace_id: str | None = None
    step_index: int | None = None
    source_state: dict[str, float]
    observed_state: dict[str, float]
    action_before_degradation: dict[str, float]
    executed_action: dict[str, float]
    failure_parameters: dict[str, float]
    disturbance_values: dict[str, float]
    sensor_error_values: dict[str, float]
    next_state: dict[str, float]
    time_step_seconds: float
    generation_seed: int
    simulator_config_sha256: str
    git_commit: str
    dirty_tree: bool
    timestamp_utc: str

    @model_validator(mode="after")
    def vectors_have_stable_schema(self) -> "PlantTransitionRecord":
        if tuple(self.source_state) != STATE_NAMES or tuple(self.next_state) != STATE_NAMES:
            raise ValueError("Formal state fields are not in the required order")
        if tuple(self.action_before_degradation) != ACTION_NAMES or tuple(self.executed_action) != ACTION_NAMES:
            raise ValueError("Action fields are not in the required order")
        return self


def load_dataset_config(path: str | Path) -> PlantDatasetConfig:
    return PlantDatasetConfig.model_validate(load_yaml(path))


def _git_metadata() -> tuple[str, bool]:
    commit = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    dirty = bool(subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True, check=True).stdout.strip())
    return commit, dirty


def _atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + f".tmp-{os.getpid()}")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    os.replace(temporary, path)


def _sample(rng: np.random.Generator, bounds: tuple[float, float], index: int, count: int) -> float:
    lower, upper = bounds
    if lower == upper:
        return lower
    fraction = ((index * 0.6180339887498949) % 1.0 + rng.random() / max(count, 1)) % 1.0
    return float(lower + (upper - lower) * fraction)


def _commands(values: dict[str, float], timestamp: float) -> ControllerOutput:
    return ControllerOutput(
        timestamp_seconds=timestamp,
        control_commands=ControlCommands(**values),
        stabilization_targets=StabilizationTargets(target_pitch_deg=0, target_roll_deg=0, target_airspeed_kts=135, target_altitude_ft=5000),
        navigation_commands=NavigationCommands(target_heading_deg=0),
        emergency_mode="stabilize",
        safety_decision=SafetyDecision(status="not_checked", ai_action_accepted=True, fallback_activated=False, explanation="formal plant data generation"),
        confidence=1.0,
    )


def _action(rng: np.random.Generator, index: int, saturated: bool = False) -> dict[str, float]:
    if saturated:
        sign = -1.0 if index % 2 else 1.0
        return dict(zip(ACTION_NAMES, (sign, -sign, sign, float(index % 2), float((index + 1) % 2))))
    surface_scale = 0.35 if index % 3 == 0 else 1.0
    return {
        "elevator": float(rng.uniform(-surface_scale, surface_scale)),
        "aileron": float(rng.uniform(-surface_scale, surface_scale)),
        "rudder": float(rng.uniform(-surface_scale, surface_scale)),
        "throttle_left": float(rng.uniform(0, 1)),
        "throttle_right": float(rng.uniform(0, 1)),
    }


def _failure(failure_id: str, kind: FailureType, severity: float, parameters: dict[str, Any] | None = None) -> FailureDefinition:
    return FailureDefinition(
        failure_id=failure_id, failure_type=kind, affected_subsystem=failure_id,
        severity=severity, activation="start", permanent=True, observable=True,
        detected=True, parameters=parameters or {},
    )


def _scenario(config: PlantDatasetConfig, aircraft: AircraftConfig, rng: np.random.Generator, index: int, scenario_id: str, seed: int) -> tuple[ScenarioConfig, dict[str, float]]:
    state = {name: _sample(rng, config.state_ranges[name], index, config.one_step_samples) for name in ("airspeed_kts", "pitch_deg", "bank_deg", "terrain_clearance_ft")}
    right = _sample(rng, config.failure_ranges["right_thrust_availability"], index, config.one_step_samples)
    aileron = _sample(rng, config.failure_ranges["aileron_effectiveness"], index + 3, config.one_step_samples)
    delay = _sample(rng, config.failure_ranges["actuator_delay_seconds"], index + 7, config.one_step_samples)
    crosswind = _sample(rng, config.disturbance_ranges.get("crosswind_kts", (0.0, 0.0)), index + 11, config.one_step_samples)
    turbulence = _sample(rng, config.disturbance_ranges.get("turbulence_intensity", (0.0, 0.0)), index + 13, config.one_step_samples)
    altitude = 5000.0
    failures = [
        _failure("left_engine", FailureType.LEFT_ENGINE_FAILURE, 1.0),
        _failure("right_availability", FailureType.PARTIAL_THRUST_LOSS, 1.0 - right, {"engine": "right"}),
        _failure("aileron_effectiveness", FailureType.REDUCED_AILERON, 1.0 - aileron),
        _failure("actuator_delay", FailureType.ACTUATOR_DELAY, 1.0, {"maximum_delay_seconds": delay}),
        _failure("crosswind", FailureType.CROSSWIND_INCREASE, 1.0, {"maximum_wind_kts": crosswind}),
    ]
    scenario = ScenarioConfig.model_validate({
        "scenario_id": scenario_id, "description": "Formal plant calibration sample",
        "seed": seed, "duration_seconds": max(2.0, (config.pre_roll_steps + config.trace_length_steps + 2) * aircraft.time_step_seconds),
        "expected_recoverability": "unknown",
        "initial_state": {"altitude_ft": altitude, "airspeed_kts": state["airspeed_kts"], "pitch_deg": state["pitch_deg"], "roll_deg": state["bank_deg"], "yaw_deg": 0, "heading_deg": 0, "latitude_deg": 0, "longitude_deg": 0},
        "airports": [],
        "environment": {"wind_speed_kts": abs(crosswind), "wind_direction_deg": 90, "turbulence_intensity": turbulence, "visibility_nm": 20, "terrain_clearance_ft": state["terrain_clearance_ft"]},
        "failures": [item.model_dump(mode="json") for item in failures],
        "termination": {"loss_of_control_roll_deg": 170, "stall_timeout_seconds": 100, "overspeed_timeout_seconds": 100},
    })
    return scenario, {"left_thrust_availability": 0.0, "right_thrust_availability": right, "aileron_effectiveness": aileron, "actuator_delay_seconds": delay, "crosswind_kts": crosswind, "turbulence_intensity": turbulence}


def _formal_state(simulator: SimpleAircraftSimulator, terrain_datum_ft: float) -> dict[str, float]:
    audit = simulator.audit_snapshot(); true = audit["true_state"]; previous = audit["applied_control_commands"]
    values = (
        true["airspeed_kts"], true["pitch_deg"], true["roll_deg"], true["vertical_speed_fpm"],
        true["altitude_ft"] - terrain_datum_ft, previous["elevator"], previous["aileron"],
        previous["rudder"], previous["throttle_left"], previous["throttle_right"],
    )
    return {name: float(value) for name, value in zip(STATE_NAMES, values)}


def _observed_state(observation, true_state: dict[str, float], errors: dict[str, float]) -> dict[str, float]:
    values = dict(true_state)
    values["airspeed_kts"] = float(observation.aircraft_state.airspeed_kts + errors["airspeed_kts"])
    values["bank_deg"] = float(observation.aircraft_state.roll_deg + errors["bank_deg"])
    values["terrain_clearance_ft"] = float(true_state["terrain_clearance_ft"] + errors["terrain_clearance_ft"])
    return values


def _make_record(config: PlantDatasetConfig, aircraft: AircraftConfig, simulator: SimpleAircraftSimulator, observation, terrain_datum: float, proposed: dict[str, float], failure: dict[str, float], errors: dict[str, float], sample_id: str, scenario_id: str, seed: int, kind: str, config_hash: str, commit: str, dirty: bool, trace_id: str | None = None, step_index: int | None = None) -> tuple[PlantTransitionRecord, Any]:
    source = _formal_state(simulator, terrain_datum)
    observed = _observed_state(observation, source, errors)
    next_observation = simulator.step(_commands(proposed, simulator.time_seconds))
    next_state = _formal_state(simulator, terrain_datum)
    executed = simulator.audit_snapshot()["applied_control_commands"]
    pitch_base = source["pitch_deg"] + executed["elevator"] * aircraft.pitch_rate_deg_s * aircraft.time_step_seconds
    bank_base = source["bank_deg"] + (executed["aileron"] * failure["aileron_effectiveness"] + 0.12 * (failure["left_thrust_availability"] - failure["right_thrust_availability"])) * aircraft.roll_rate_deg_s * aircraft.time_step_seconds
    disturbances = {"crosswind_kts": failure["crosswind_kts"], "pitch_delta_deg": next_state["pitch_deg"] - pitch_base, "roll_delta_deg": next_state["bank_deg"] - bank_base}
    record = PlantTransitionRecord(
        split=config.split, record_kind=kind, sample_id=sample_id, scenario_id=scenario_id,
        trace_id=trace_id, step_index=step_index, source_state=source, observed_state=observed,
        action_before_degradation={name: float(proposed[name]) for name in ACTION_NAMES},
        executed_action={name: float(executed[name]) for name in ACTION_NAMES}, failure_parameters=failure,
        disturbance_values=disturbances, sensor_error_values=errors, next_state=next_state,
        time_step_seconds=aircraft.time_step_seconds, generation_seed=seed,
        simulator_config_sha256=config_hash, git_commit=commit, dirty_tree=dirty,
        timestamp_utc=config.protocol_timestamp_utc,
    )
    return record, next_observation


def generate_dataset(config: PlantDatasetConfig) -> dict[str, Any]:
    started = perf_counter(); commit, dirty = _git_metadata()
    if dirty and not config.allow_dirty_tree:
        raise RuntimeError("Refusing formal plant data generation from a dirty tree")
    aircraft = load_config(config.aircraft_config, AircraftConfig); config_hash = file_hash(config.aircraft_config)
    rng = np.random.default_rng(config.seed); records: list[PlantTransitionRecord] = []
    for index in range(config.one_step_samples):
        seed = config.seed * 100000 + index; scenario_id = f"{config.split}-one-{index:06d}"
        scenario, failure = _scenario(config, aircraft, rng, index, scenario_id, seed)
        simulator = SimpleAircraftSimulator(aircraft, scenario); observation = simulator.reset(seed)
        terrain_datum = scenario.initial_state.altitude_ft - scenario.environment["terrain_clearance_ft"]
        prior = _action(rng, index)
        for _ in range(config.pre_roll_steps): observation = simulator.step(_commands(prior, simulator.time_seconds))
        errors = {name: _sample(rng, config.sensor_error_ranges[name], index, config.one_step_samples) for name in ("airspeed_kts", "bank_deg", "terrain_clearance_ft")}
        proposed = _action(rng, index, saturated=index % 5 == 0)
        record, _ = _make_record(config, aircraft, simulator, observation, terrain_datum, proposed, failure, errors, f"{config.split}-sample-{index:06d}", scenario_id, seed, "one_step", config_hash, commit, dirty)
        records.append(record)
    for trace_index in range(config.trace_count):
        seed = config.seed * 100000 + config.one_step_samples + trace_index; scenario_id = f"{config.split}-trace-{trace_index:04d}"
        scenario, failure = _scenario(config, aircraft, rng, trace_index + config.one_step_samples, scenario_id, seed)
        simulator = SimpleAircraftSimulator(aircraft, scenario); observation = simulator.reset(seed)
        terrain_datum = scenario.initial_state.altitude_ft - scenario.environment["terrain_clearance_ft"]
        for step in range(config.trace_length_steps):
            errors = {name: _sample(rng, config.sensor_error_ranges[name], step + trace_index, config.trace_length_steps) for name in ("airspeed_kts", "bank_deg", "terrain_clearance_ft")}
            proposed = _action(rng, step + trace_index, saturated=step % 9 == 0)
            record, observation = _make_record(config, aircraft, simulator, observation, terrain_datum, proposed, failure, errors, f"{config.split}-trace-{trace_index:04d}-step-{step:04d}", scenario_id, seed, "trace", config_hash, commit, dirty, scenario_id, step)
            records.append(record)
    output = Path(config.output_directory); lines = "".join(json.dumps(item.model_dump(mode="json"), sort_keys=False, separators=(",", ":")) + "\n" for item in records)
    transitions_path = output / "transitions.jsonl"; _atomic_text(transitions_path, lines)
    manifest = {
        "schema_version": 1, "protocol_version": config.protocol_version, "split": config.split,
        "seed": config.seed, "one_step_samples": config.one_step_samples, "trace_count": config.trace_count,
        "trace_length_steps": config.trace_length_steps, "record_count": len(records),
        "sample_ids_sha256": canonical_hash([item.sample_id for item in records]),
        "scenario_ids_sha256": canonical_hash(sorted({item.scenario_id for item in records})),
        "transitions_sha256": hashlib.sha256(lines.encode("utf-8")).hexdigest(),
        "configuration_sha256": canonical_hash(config.model_dump(mode="json")),
        "simulator_config_sha256": config_hash, "git_commit": commit, "dirty_tree": dirty,
        "generation_runtime_seconds": perf_counter() - started,
    }
    manifest["manifest_sha256"] = canonical_hash(manifest); _atomic_text(output / "manifest.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return manifest


def load_records(directory: str | Path) -> list[PlantTransitionRecord]:
    return [PlantTransitionRecord.model_validate_json(line) for line in (Path(directory) / "transitions.jsonl").read_text(encoding="utf-8").splitlines()]


def assert_split_isolation(calibration_directory: str | Path, validation_directory: str | Path) -> dict[str, bool]:
    calibration = load_records(calibration_directory); validation = load_records(validation_directory)
    checks = {
        "sample_ids_disjoint": {item.sample_id for item in calibration}.isdisjoint(item.sample_id for item in validation),
        "scenario_ids_disjoint": {item.scenario_id for item in calibration}.isdisjoint(item.scenario_id for item in validation),
        "seeds_disjoint": {item.generation_seed for item in calibration}.isdisjoint(item.generation_seed for item in validation),
    }
    if not all(checks.values()): raise ValueError(f"Calibration/validation isolation failed: {checks}")
    return checks
